# Generated by Django 4.1.3 on 2022-11-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='priority1',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='task1',
        ),
    ]
