# Generated by Django 4.1.3 on 2022-12-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0002_rename_priority_task_priority1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date1',
            field=models.DateField(default='1899-08-28'),
            preserve_default=False,
        ),
    ]
